---
- apt: name=apt-transport-https state=latest

- apt_key: >
    id=C7A7DA52
    url=http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x226AE980C7A7DA52
    state=present
    keyring=/etc/apt/trusted.gpg.d/datadog.gpg

- apt_repository: repo='deb http://apt.datadoghq.com/ stable main' state=present update_cache=yes

- apt: name=datadog-agent state=latest update_cache=yes
